# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/solid': '@stable'
    'multimedia/libkcddb': '@same'

Options:
    require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
