# SPDX-FileCopyrightText: 2024, 2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: audex
confinement: strict
grade: stable
base: core24
adopt-info: audex
apps:
  audex:
    extensions:
      - kde-neon-6
    common-id: org.kde.audex.desktop
    desktop: usr/share/applications/org.kde.audex.desktop
    command: usr/bin/audex
    plugs:
      - audio-record
      - home
      - optical-drive
      - system-backup
      - mount-observe
      - hardware-observe
      - raw-usb
      - removable-media
    environment:
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/plugins/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins"
      QML_IMPORT_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qml:/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qml"
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.audex
    bus: session
parts:
  libkcddb:
    plugin: cmake
    source: https://invent.kde.org/multimedia/libkcddb.git
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
  audex:
    after:
      - libkcddb
    parse-info:
      - usr/share/metainfo/org.kde.audex.appdata.xml
    plugin: cmake
    build-packages:
      - libxkbcommon-dev
      - libcdio-dev
      - libcdio-cdda-dev
      - libcdio-paranoia-dev
      - libpulse0
    stage-packages:
      - libpulse0
      - libasound2
      - libasound2-plugins
      - libasound2-data
      - flac
      - lame
      - opus-tools
      - vorbis-tools
      - faac
      - libxkbcommon0
      - libcdio19t64
      - libcdio-cdda2t64
      - libcdio-paranoia2t64
      - libaudio2
    source: .
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  cleanup:
    after:
      - audex
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

